// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPProxyService is deliberately transport-only. The official TypeScript MCP
 * client still owns protocol negotiation, schema parsing and tool calls; this
 * loopback proxy only avoids WebView CORS restrictions and applies desktop proxy
 * settings without exposing a general-purpose forward proxy.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3444421866, id);
}

export function CreateSession(targetURL: string, headersText: string, proxyMode: string, proxyURL: string): $CancellablePromise<$models.MCPProxySession> {
    return $Call.ByID(2018222642, targetURL, headersText, proxyMode, proxyURL);
}
