// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChooseFolder(): $CancellablePromise<string> {
    return $Call.ByID(3092180594);
}

export function ExecuteRename(request: $models.RenameRequest): $CancellablePromise<$models.RenameExecutionResult> {
    return $Call.ByID(2885873260, request);
}

export function ListFiles(paths: string[] | null, recursive: boolean): $CancellablePromise<$models.RenameFileInfo[] | null> {
    return $Call.ByID(1945688238, paths, recursive);
}

export function PreviewRename(request: $models.RenameRequest): $CancellablePromise<$models.RenamePreview> {
    return $Call.ByID(1464297143, request);
}

export function UndoLastRename(): $CancellablePromise<$models.RenameExecutionResult> {
    return $Call.ByID(2228113515);
}
