// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileInspection {
    "path": string;
    "name": string;
    "size": number;
    "modified": string;
    "mime": string;
    "algorithm": string;
    "digest": string;
    "width"?: number;
    "height"?: number;
    "utf8": boolean;
    "lineEnding"?: string;
}

export interface RenameExecutionResult {
    "success": boolean;
    "renamed": number;
    "items": RenamePlanItem[] | null;
    "canUndo": boolean;
    "message": string;
}

export interface RenameFileInfo {
    "path": string;
    "name": string;
    "directory": string;
    "extension": string;
    "size": number;
    "modified": string;
}

export interface RenamePlanItem {
    "sourcePath": string;
    "targetPath": string;
    "oldName": string;
    "newName": string;
    "status": string;
    "error": string;
}

export interface RenamePreview {
    "items": RenamePlanItem[] | null;
    "total": number;
    "matched": number;
    "ready": number;
    "conflicts": number;
}

export interface RenameRequest {
    "paths": string[] | null;
    "recursive": boolean;
    "matchMode": string;
    "matchPattern": string;
    "matchFullName": boolean;
    "operation": string;
    "find": string;
    "replacement": string;
    "useRegex": boolean;
    "prefix": string;
    "suffix": string;
    "start": number;
    "step": number;
    "width": number;
    "includeExtension": boolean;
    "sortBy": string;
}

export interface TextFileResult {
    "path": string;
    "content": string;
}
