// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckPort(host: string, port: number, timeoutMS: number): $CancellablePromise<$models.NetworkResult> {
    return $Call.ByID(2490371867, host, port, timeoutMS);
}

export function DNSQuery(host: string, recordType: string, timeoutMS: number): $CancellablePromise<$models.NetworkResult> {
    return $Call.ByID(797099277, host, recordType, timeoutMS);
}

export function FindProcesses(searchType: string, query: string): $CancellablePromise<$models.ProcessResult> {
    return $Call.ByID(39264652, searchType, query);
}

export function HTTPRequest(method: string, targetURL: string, headersText: string, body: string, proxyMode: string, proxyURL: string, timeoutMS: number): $CancellablePromise<$models.HTTPResult> {
    return $Call.ByID(4065340473, method, targetURL, headersText, body, proxyMode, proxyURL, timeoutMS);
}

export function Ping(host: string, count: number, timeoutMS: number, packetSize: number): $CancellablePromise<$models.NetworkResult> {
    return $Call.ByID(2113597680, host, count, timeoutMS, packetSize);
}

export function TerminateProcess(pid: number): $CancellablePromise<$models.NetworkResult> {
    return $Call.ByID(3054243780, pid);
}
