// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GreetService from "./greetservice.js";
import * as NetworkService from "./networkservice.js";
export {
    GreetService,
    NetworkService
};

export type {
    HTTPResult,
    NetworkResult
} from "./models.js";
