// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HTTPResult {
    "success": boolean;
    "status": string;
    "statusCode": number;
    "headers": { [_ in string]?: string[] | null } | null;
    "body": string;
    "durationMs": number;
}

export interface NetworkResult {
    "success": boolean;
    "output": string;
    "durationMs": number;
}
