// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIProxyService keeps the TypeScript AI SDK in charge of provider protocols,
 * while all external HTTP traffic is sent by Go. Each session is restricted to
 * the origin of the first provider request and protected by an unguessable token.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1608563474, id);
}

export function CreateSession(targetURL: string, proxyMode: string, proxyURL: string): $CancellablePromise<$models.AIProxySession> {
    return $Call.ByID(3982535786, targetURL, proxyMode, proxyURL);
}
