// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AIProxySession {
    "success": boolean;
    "id": string;
    "endpoint": string;
    "token": string;
    "error": string;
}
