// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AES(mode: string, input: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(2879526445, mode, input, password);
}

export function GenerateIdentifier(kind: string, length: number): $CancellablePromise<string> {
    return $Call.ByID(3990327078, kind, length);
}

export function GenerateRSA(usage: string): $CancellablePromise<$models.RSAKeyPair> {
    return $Call.ByID(2802232609, usage);
}

export function Hash(input: string, algorithm: string, useHMAC: boolean, secret: string): $CancellablePromise<string> {
    return $Call.ByID(439820334, input, algorithm, useHMAC, secret);
}

export function JWT(mode: string, input: string, secret: string): $CancellablePromise<string> {
    return $Call.ByID(2807967491, mode, input, secret);
}

export function RSA(action: string, input: string, signature: string, publicKeyPEM: string, privateKeyPEM: string): $CancellablePromise<$models.RSAOperationResult> {
    return $Call.ByID(2354774416, action, input, signature, publicKeyPEM, privateKeyPEM);
}
