// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RSAKeyPair {
    "publicKey": string;
    "privateKey": string;
}

export interface RSAOperationResult {
    "output": string;
    "valid": boolean;
}
