import { Button } from "@/components/ui/button"
import { uiText } from "@/lib/i18n"
import { inputClass,useFrontendToolsPageViewModel } from "@/models/FrontendToolsPageModel"
import { Code2,Copy,Palette,Ruler,Sparkles,SunMedium } from "lucide-react"

export default function FrontendToolsPage() {
 const { language, foreground, setForeground, background, setBackground, angle, setAngle, baseSize, setBaseSize, viewportWidth, setViewportWidth, pixelValue, setPixelValue, shadow, setShadow, svg, setSVG, details, contrast, gradient, shadowCSS, svgDataURL, copy } = useFrontendToolsPageViewModel()
return <section className="page-shell"><div className="mx-auto w-full max-w-7xl"><div className="mb-6"><div className="mb-2 flex items-center gap-2 text-sm text-muted-foreground"><Sparkles className="size-4" />{uiText("开发工具")}</div><h1 className="text-3xl font-semibold tracking-tight">{uiText("颜色与前端")}</h1><p className="mt-2 text-sm text-muted-foreground">{uiText("颜色格式、对比度、渐变、阴影、CSS 单位与 SVG Data URL，全部在本地计算。")}</p></div><div className="grid gap-4 xl:grid-cols-2">
    <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2 font-medium"><Palette className="size-4" />{uiText("颜色转换")}</div><div className="mt-4 grid gap-3 sm:grid-cols-[4rem_1fr]"><input type="color" className="app-interactive h-10 w-16 rounded border bg-transparent" value={details.value?.hex ?? "#000000"} onChange={(event) => setForeground(event.target.value)} /><input className={inputClass} value={foreground} onChange={(event) => setForeground(event.target.value)} /></div>{details.error ? <div className="mt-3 text-sm text-destructive">{details.error}</div> : details.value && <div className="mt-3 space-y-2">{[details.value.hex, details.value.rgb, details.value.hsl, details.value.oklch].map((value) => <button key={value} className="app-interactive block w-full rounded-lg border bg-muted/20 px-3 py-2 text-left font-mono text-xs" onClick={() => copy(value)}>{value}</button>)}</div>}</article>
    <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2 font-medium"><SunMedium className="size-4" />{uiText("对比度与渐变")}</div><div className="mt-4 grid grid-cols-2 gap-3"><input className={inputClass} value={foreground} onChange={(event) => setForeground(event.target.value)} /><input className={inputClass} value={background} onChange={(event) => setBackground(event.target.value)} /></div><div className="mt-3 rounded-lg border p-6 text-center font-medium" style={{ color: foreground, background }}>Quick Contrast · {contrast.toFixed(2)}:1</div><div className="mt-2 text-xs text-muted-foreground">{language === "en-US" ? `Normal text AA: ${contrast >= 4.5 ? "Passed" : "Failed"} · Large text AA: ${contrast >= 3 ? "Passed" : "Failed"}` : `普通文本 AA：${contrast >= 4.5 ? uiText("通过") : uiText("未通过")} · 大文本 AA：${contrast >= 3 ? uiText("通过") : uiText("未通过")}`}</div><div className="mt-4 h-20 rounded-lg border" style={{ background: gradient }} /><div className="mt-2 flex items-center gap-2"><input className={inputClass} type="number" value={angle} onChange={(event) => setAngle(Number(event.target.value))} /><Button variant="outline" onClick={() => copy(`background: ${gradient};`)}><Copy />CSS</Button></div></article>
    <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2 font-medium"><Ruler className="size-4" />{uiText("CSS 单位与阴影")}</div><div className="mt-4 grid grid-cols-3 gap-2"><label className="text-xs text-muted-foreground">px<input className={inputClass} type="number" value={pixelValue} onChange={(event) => setPixelValue(Number(event.target.value))} /></label><label className="text-xs text-muted-foreground">{uiText("根字号")}<input className={inputClass} type="number" value={baseSize} onChange={(event) => setBaseSize(Number(event.target.value))} /></label><label className="text-xs text-muted-foreground">{uiText("视口宽")}<input className={inputClass} type="number" value={viewportWidth} onChange={(event) => setViewportWidth(Number(event.target.value))} /></label></div><div className="mt-3 rounded-lg border bg-muted/20 p-3 font-mono text-sm">{(pixelValue / baseSize).toFixed(4)} rem · {(pixelValue / viewportWidth * 100).toFixed(4)} vw</div><div className="mt-4 grid grid-cols-4 gap-2">{(["x", "y", "blur", "spread"] as const).map((key) => <label key={key} className="text-xs text-muted-foreground">{key}<input className={inputClass} type="number" value={shadow[key]} onChange={(event) => setShadow({ ...shadow, [key]: Number(event.target.value) })} /></label>)}</div><button type="button" className="app-interactive mt-5 h-20 w-full rounded-xl bg-background" style={{ boxShadow: shadowCSS }} onClick={() => copy(`box-shadow: ${shadowCSS};`)}>{uiText("点击复制阴影 CSS")}</button></article>
    <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2 font-medium"><Code2 className="size-4" />SVG Data URL</div><textarea className="app-interactive mt-4 h-36 w-full resize-none rounded-lg border bg-background p-3 font-mono text-xs outline-none" value={svg} onChange={(event) => setSVG(event.target.value)} spellCheck={false} /><textarea className="app-interactive mt-3 h-24 w-full resize-none rounded-lg border bg-muted/20 p-3 font-mono text-xs outline-none" readOnly value={svgDataURL} /><Button className="mt-3" variant="outline" onClick={() => copy(svgDataURL)}><Copy />{uiText("复制 Data URL")}</Button></article>
  </div></div></section>
}
