import { Button } from "@/components/ui/button"
import { Dialog,DialogClose,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"
import { writeClipboard } from "@/lib/clipboard"
import { uiText } from "@/lib/i18n"
import { inputClass,useNetworkPageViewModel } from "@/models/NetworkPageModel"
import { Activity,Copy,Play,Plus,Power,Router,Search,Sparkles,Trash2 } from "lucide-react"
import { toast } from "sonner"

export default function NetworkPage() {
 const { proxy, t, mode, setMode, host, setHost, pingCount, setPingCount, pingTimeoutMS, setPingTimeoutMS, pingPacketSize, setPingPacketSize, port, setPort, recordType, setRecordType, cidr, setCIDR, method, setMethod, url, setURL, headers, setHeaders, body, setBody, curl, setCurl, processSearchType, setProcessSearchType, processQuery, setProcessQuery, processes, processCanTerminate, setProcessCanTerminate, pendingTermination, setPendingTermination, terminatingPID, output, setOutput, running, curlPreview, urlInspection, changeURLParameters, run, importCurl, findProcesses, terminateProcess, modes } = useNetworkPageViewModel()
return (
    <section className="page-shell">
      <div className="mx-auto w-full max-w-7xl">
        <div className="mb-6"><div className="mb-2 flex items-center gap-2 text-sm text-muted-foreground"><Sparkles className="size-4" />{uiText("开发工具")}</div><h1 className="text-3xl font-semibold tracking-tight">{uiText("网络工具")}</h1><p className="mt-2 text-sm text-muted-foreground">{uiText("网络诊断、HTTP/cURL 双向转换，以及本机端口和进程查询。")}</p></div>
        <div className="mb-4 flex flex-wrap gap-2">{modes.map(({ id, label, icon: Icon }) => <Button key={id} variant={mode === id ? "default" : "outline"} onClick={() => { setMode(id); setOutput("") }}><Icon />{label}</Button>)}</div>
        <div className="overflow-hidden rounded-xl border bg-card shadow-sm">
          <div className="border-b p-4">
            {mode === "ping" && <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input className={inputClass} value={host} onChange={(event) => setHost(event.target.value)} placeholder={uiText("主机名或 IP")} /><Button onClick={run} disabled={running}><Activity />Ping</Button></div><div className="grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-xs text-muted-foreground"><span>{uiText("次数（1–20）")}</span><input className={inputClass} type="number" min={1} max={20} value={pingCount} onChange={(event) => setPingCount(Number(event.target.value))} /></label><label className="space-y-1 text-xs text-muted-foreground"><span>{uiText("总超时（ms）")}</span><input className={inputClass} type="number" min={100} max={60000} step={100} value={pingTimeoutMS} onChange={(event) => setPingTimeoutMS(Number(event.target.value))} /></label><label className="space-y-1 text-xs text-muted-foreground"><span>{uiText("数据包（字节）")}</span><input className={inputClass} type="number" min={1} max={65500} value={pingPacketSize} onChange={(event) => setPingPacketSize(Number(event.target.value))} /></label></div></div>}
            {mode === "dns" && <div className="grid gap-3 sm:grid-cols-[1fr_8rem_auto]"><input className={inputClass} value={host} onChange={(event) => setHost(event.target.value)} placeholder={uiText("域名")} /><select className={inputClass} value={recordType} onChange={(event) => setRecordType(event.target.value)}>{["A", "AAAA", "CNAME", "MX", "NS", "TXT"].map((value) => <option key={value}>{value}</option>)}</select><Button onClick={run} disabled={running}><Search />{uiText("查询")}</Button></div>}
            {mode === "port" && <div className="grid gap-3 sm:grid-cols-[1fr_8rem_auto]"><input className={inputClass} value={host} onChange={(event) => setHost(event.target.value)} /><input className={inputClass} type="number" min={1} max={65535} value={port} onChange={(event) => setPort(Number(event.target.value))} /><Button onClick={run} disabled={running}><Router />{uiText("连接")}</Button></div>}
            {mode === "cidr" && <div className="grid gap-3 sm:grid-cols-[1fr_auto]"><input className={inputClass} value={cidr} onChange={(event) => setCIDR(event.target.value)} placeholder="192.168.1.10/24" /><Button onClick={run}><Play />{uiText("计算")}</Button></div>}
            {mode === "url" && <div className="space-y-4">
              <input className={inputClass} value={url} onChange={(event) => setURL(event.target.value)} placeholder="https://user@example.com:8443/path?name=Quick#section" spellCheck={false} />
              {urlInspection.error ? <div className="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{urlInspection.error}</div> : urlInspection.value && <>
                <div className="grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-4">{[[uiText("协议"), urlInspection.value.protocol], [uiText("主机"), urlInspection.value.hostname], [uiText("端口"), urlInspection.value.port], [uiText("路径"), urlInspection.value.pathname], ["Origin", urlInspection.value.origin], ["Fragment", urlInspection.value.hash || "—"]].map(([label, value]) => <div key={label} className="min-w-0 rounded-lg border bg-muted/20 p-3"><div className="text-muted-foreground">{label}</div><div className="mt-1 truncate font-mono" title={value}>{value}</div></div>)}</div>
                <div className="overflow-hidden rounded-lg border"><div className="flex items-center justify-between border-b bg-muted/30 px-3 py-2 text-xs font-medium"><span>{uiText("Query 参数 ·")}{urlInspection.value.parameters.length}</span><Button variant="ghost" size="xs" onClick={() => changeURLParameters((entries) => [...entries, ["key", "value"]])}><Plus />{uiText("添加")}</Button></div>{urlInspection.value.parameters.length ? urlInspection.value.parameters.map((parameter, index) => <div key={`${index}-${parameter.key}`} className="grid grid-cols-[1fr_1fr_auto] gap-2 border-b p-2 last:border-0"><input className={inputClass} value={parameter.key} onChange={(event) => changeURLParameters((entries) => entries.map((entry, itemIndex) => itemIndex === index ? [event.target.value, entry[1]] : entry))} aria-label={`参数 ${index + 1} 名称`} /><input className={inputClass} value={parameter.value} onChange={(event) => changeURLParameters((entries) => entries.map((entry, itemIndex) => itemIndex === index ? [entry[0], event.target.value] : entry))} aria-label={`参数 ${index + 1} 值`} /><Button variant="ghost" size="icon" onClick={() => changeURLParameters((entries) => entries.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></Button></div>) : <div className="p-4 text-center text-xs text-muted-foreground">{uiText("没有查询参数")}</div>}</div>
              </>}
            </div>}
            {mode === "process" && <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-[9rem_1fr_auto]"><select className={inputClass} value={processSearchType} onChange={(event) => { setProcessSearchType(event.target.value as typeof processSearchType); setProcessQuery(""); setProcessCanTerminate(false) }}><option value="port">{uiText("按端口")}</option><option value="pid">{uiText("按 PID")}</option><option value="name">{uiText("按程序名")}</option></select><input className={inputClass} value={processQuery} onChange={(event) => { setProcessQuery(event.target.value); setProcessCanTerminate(false) }} placeholder={processSearchType === "name" ? uiText("程序名；留空显示全部") : `${processSearchType.toUpperCase()}；留空显示全部`} /><Button onClick={findProcesses} disabled={running}><Search />{processQuery.trim() ? uiText("搜索") : uiText("显示全部")}</Button></div><div className="max-h-[32rem] overflow-auto rounded-lg border"><div className="sticky top-0 z-10 grid min-w-[36rem] grid-cols-[6rem_1fr_1fr_5rem] bg-muted px-3 py-2 text-xs font-medium text-muted-foreground shadow-[0_1px_0_var(--border)]"><span>PID</span><span>{uiText("程序")}</span><span>{uiText("本地 TCP 端口")}</span><span></span></div>{processes.length ? processes.map((process) => <div key={process.pid} className="grid min-w-[36rem] grid-cols-[6rem_1fr_1fr_5rem] items-center border-t px-3 py-2 text-sm"><code>{process.pid}</code><span className="truncate" title={process.name}>{process.name}</span><span className="truncate text-muted-foreground">{process.ports.join(", ") || "—"}</span><Button variant="destructive" size="sm" disabled={!processCanTerminate} title={processCanTerminate ? uiText("关闭此进程") : uiText("输入条件并搜索后才可关闭")} onClick={() => setPendingTermination(process)}><Power />{uiText("关闭")}</Button></div>) : <div className="border-t p-6 text-center text-sm text-muted-foreground">{uiText("留空可显示全部进程；只有带条件的搜索结果允许关闭。")}</div>}</div></div>}
            {mode === "http" && <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-[8rem_1fr_auto]"><select className={inputClass} value={method} onChange={(event) => setMethod(event.target.value)}>{["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"].map((value) => <option key={value}>{value}</option>)}</select><input className={inputClass} value={url} onChange={(event) => setURL(event.target.value)} placeholder="https://example.com" /><Button onClick={run} disabled={running}><Play />{uiText("发送 HTTP")}</Button></div><div className="grid gap-3 md:grid-cols-2"><textarea className={`${inputClass} h-28 resize-none font-mono`} value={headers} onChange={(event) => setHeaders(event.target.value)} placeholder="Header: value" /><textarea className={`${inputClass} h-28 resize-none font-mono`} value={body} onChange={(event) => setBody(event.target.value)} placeholder={uiText("请求体（可选）")} /></div><div className="grid gap-3 lg:grid-cols-2"><div className="space-y-2"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>HTTP → cURL</span><Button variant="outline" size="sm" onClick={() => setCurl(curlPreview)}>{uiText("写入编辑器")}</Button></div><pre className="h-32 overflow-auto whitespace-pre-wrap break-all rounded-lg border bg-muted/30 p-3 text-xs">{curlPreview}</pre></div><div className="space-y-2"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>cURL → HTTP</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => importCurl(false)}>{uiText("转换")}</Button><Button size="sm" onClick={() => importCurl(true)} disabled={running}>{uiText("转换并执行")}</Button></div></div><textarea className={`${inputClass} h-32 resize-none font-mono text-xs`} value={curl} onChange={(event) => setCurl(event.target.value)} placeholder={uiText("粘贴 curl 命令…")} /></div></div><div className="flex items-center gap-2 rounded-lg border bg-muted/30 p-3 text-xs"><span className="min-w-0 flex-1">{uiText("代理：")}{proxy.mode === "system" ? uiText("系统/环境") : proxy.mode === "custom" ? proxy.url || uiText("自定义（未填写）") : uiText("不使用")}</span><Button variant="ghost" size="icon-xs" onClick={async () => { await writeClipboard(curlPreview); toast.success(uiText("cURL 命令已复制")) }}><Copy /></Button></div></div>}
          </div>
          {mode !== "process" && mode !== "url" && <pre className="min-h-52 max-h-[32rem] overflow-auto whitespace-pre-wrap break-words bg-muted/20 p-4 font-mono text-sm leading-6">{t(running ? "执行中…" : output || "执行后显示结果")}</pre>}
          {mode === "process" && output && <div className="border-t bg-muted/20 px-4 py-3 text-xs text-muted-foreground">{output}</div>}
        </div>
        <Dialog open={Boolean(pendingTermination)} onOpenChange={(open) => { if (!open && terminatingPID === null) setPendingTermination(null) }}>
          <DialogContent className="max-w-md">
            <DialogHeader><DialogTitle>{uiText("确认强制关闭进程")}</DialogTitle><DialogDescription>{uiText("此操作可能导致未保存的数据丢失，请确认目标进程无误。")}</DialogDescription></DialogHeader>
            {pendingTermination && <div className="mx-5 rounded-lg border bg-muted/30 p-3 text-sm"><div className="font-medium">{pendingTermination.name}</div><code className="mt-1 block text-xs text-muted-foreground">PID {pendingTermination.pid}</code></div>}
            <DialogFooter><DialogClose asChild><Button variant="outline" disabled={terminatingPID !== null}>{uiText("取消")}</Button></DialogClose><Button variant="destructive" disabled={!pendingTermination || terminatingPID !== null} onClick={() => pendingTermination && void terminateProcess(pendingTermination)}><Power />{terminatingPID !== null ? uiText("正在关闭…") : uiText("强制关闭")}</Button></DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </section>
  )
}
