// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService stores long-lived application settings outside the WebView
 * profile. This keeps them stable when the frontend dev-server port, WebView
 * origin, executable, or package format changes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Load(key: string): $CancellablePromise<string> {
    return $Call.ByID(3131915643, key);
}

export function Save(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1279210262, key, value);
}
