// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChooseFolder(): $CancellablePromise<string> {
    return $Call.ByID(4290587664);
}

export function ExecuteRename(request: $models.RenameRequest): $CancellablePromise<$models.RenameExecutionResult> {
    return $Call.ByID(3803008630, request);
}

export function ListFiles(paths: string[] | null, recursive: boolean): $CancellablePromise<$models.RenameFileInfo[] | null> {
    return $Call.ByID(1279782040, paths, recursive);
}

export function PreviewRename(request: $models.RenameRequest): $CancellablePromise<$models.RenamePreview> {
    return $Call.ByID(925079361, request);
}

export function UndoLastRename(): $CancellablePromise<$models.RenameExecutionResult> {
    return $Call.ByID(1691215633);
}
