// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CallTool(sessionID: string, name: string, argumentsJSON: string): $CancellablePromise<$models.MCPStdioCallResult> {
    return $Call.ByID(272329222, sessionID, name, argumentsJSON);
}

export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4090828064, sessionID);
}

export function Connect(command: string, argsJSON: string, envText: string, cwd: string): $CancellablePromise<$models.MCPStdioConnectResult> {
    return $Call.ByID(3933946354, command, argsJSON, envText, cwd);
}

export function ListTools(sessionID: string): $CancellablePromise<$models.MCPStdioToolsResult> {
    return $Call.ByID(1417106647, sessionID);
}
