// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HTTPResult {
    "success": boolean;
    "status": string;
    "statusCode": number;
    "headers": { [_ in string]?: string[] | null } | null;
    "body": string;
    "durationMs": number;
}

export interface MCPProxySession {
    "success": boolean;
    "id": string;
    "endpoint": string;
    "token": string;
    "error": string;
}

export interface MCPStdioCallResult {
    "success": boolean;
    "resultJson": string;
    "durationMs": number;
    "error": string;
}

export interface MCPStdioConnectResult {
    "success": boolean;
    "sessionId": string;
    "name": string;
    "version": string;
    "instructions": string;
    "capabilities": string[] | null;
    "error": string;
}

export interface MCPStdioToolsResult {
    "success": boolean;
    "toolsJson": string;
    "error": string;
}

/**
 * NavigationBatchUpdateRequest selects sites by exact IDs/titles and/or their
 * current group/list. Source filters are combined with the ID/title selector.
 * SetTargetList allows an empty TargetList to explicitly remove a site from a
 * list. The other Set* fields similarly distinguish "clear" from "unchanged".
 */
export interface NavigationBatchUpdateRequest {
    "ids"?: string[] | null;
    "titles"?: string[] | null;
    "sourceGroup"?: string;
    "sourceList"?: string;
    "matchSourceList"?: boolean;
    "targetGroup"?: string;
    "targetList"?: string;
    "setTargetList"?: boolean;
    "title"?: string;
    "setTitle"?: boolean;
    "url"?: string;
    "setUrl"?: boolean;
    "icon"?: string;
    "setIcon"?: boolean;
    "description"?: string;
    "setDescription"?: boolean;
    "size"?: string;
    "setSize"?: boolean;
}

export interface NavigationBatchUpdateResult {
    "updated": number;
    "sites": NavigationSiteChange[] | null;
    "groups": NavigationGroup[] | null;
}

export interface NavigationGroup {
    "id": string;
    "name": string;
    "items": NavigationItem[] | null;
}

export interface NavigationItem {
    "id": string;
    "title": string;
    "url": string;
    "icon": string;
    "description": string;
    "list": string;
    "size": string;
}

export interface NavigationSiteChange {
    "id": string;
    "title": string;
    "fromGroup": string;
    "fromList": string;
    "targetGroup": string;
    "targetList": string;
}

export interface NetworkResult {
    "success": boolean;
    "output": string;
    "durationMs": number;
}

export interface ProcessInfo {
    "pid": number;
    "name": string;
    "ports": number[] | null;
}

export interface ProcessResult {
    "success": boolean;
    "processes": ProcessInfo[] | null;
    "output": string;
}

export interface RenameExecutionResult {
    "success": boolean;
    "renamed": number;
    "items": RenamePlanItem[] | null;
    "canUndo": boolean;
    "message": string;
}

export interface RenameFileInfo {
    "path": string;
    "name": string;
    "directory": string;
    "extension": string;
    "size": number;
    "modified": string;
}

export interface RenamePlanItem {
    "sourcePath": string;
    "targetPath": string;
    "oldName": string;
    "newName": string;
    "status": string;
    "error": string;
}

export interface RenamePreview {
    "items": RenamePlanItem[] | null;
    "total": number;
    "matched": number;
    "ready": number;
    "conflicts": number;
}

export interface RenameRequest {
    "paths": string[] | null;
    "recursive": boolean;
    "matchMode": string;
    "matchPattern": string;
    "matchFullName": boolean;
    "operation": string;
    "find": string;
    "replacement": string;
    "useRegex": boolean;
    "prefix": string;
    "suffix": string;
    "start": number;
    "step": number;
    "width": number;
    "includeExtension": boolean;
    "sortBy": string;
}
