// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchUpdateSites edits or moves one or many durable navigation records in a
 * single transaction. Selecting only SourceGroup moves every site in that Tab;
 * adding MatchSourceList narrows it to one list (including the empty list).
 */
export function BatchUpdateSites(request: $models.NavigationBatchUpdateRequest): $CancellablePromise<$models.NavigationBatchUpdateResult> {
    return $Call.ByID(3729131792, request);
}

/**
 * DiscoverSiteIcon reads the site's declared icon URL. It returns the
 * conventional /favicon.ico URL when the page is unavailable or has no icon
 * declaration, allowing the frontend image element to perform the final check.
 */
export function DiscoverSiteIcon(value: string): $CancellablePromise<string> {
    return $Call.ByID(2536593406, value);
}

/**
 * GetNavigationGroups returns the durable navigation configuration. It does
 * not depend on the navigation page being mounted in the frontend.
 */
export function GetNavigationGroups(): $CancellablePromise<$models.NavigationGroup[] | null> {
    return $Call.ByID(481952287);
}
