// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as NavigationService from "./navigationservice.js";
export {
    NavigationService
};

export type {
    NavigationBatchUpdateRequest,
    NavigationBatchUpdateResult,
    NavigationGroup,
    NavigationItem,
    NavigationSiteChange
} from "./models.js";
