// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NavigationBatchUpdateRequest selects sites by exact IDs/titles and/or their
 * current group/list. Source filters are combined with the ID/title selector.
 * SetTargetList allows an empty TargetList to explicitly remove a site from a
 * list. The other Set* fields similarly distinguish "clear" from "unchanged".
 */
export interface NavigationBatchUpdateRequest {
    "ids"?: string[] | null;
    "titles"?: string[] | null;
    "sourceGroup"?: string;
    "sourceList"?: string;
    "matchSourceList"?: boolean;
    "targetGroup"?: string;
    "targetList"?: string;
    "setTargetList"?: boolean;
    "title"?: string;
    "setTitle"?: boolean;
    "url"?: string;
    "setUrl"?: boolean;
    "icon"?: string;
    "setIcon"?: boolean;
    "description"?: string;
    "setDescription"?: boolean;
    "size"?: string;
    "setSize"?: boolean;
}

export interface NavigationBatchUpdateResult {
    "updated": number;
    "sites": NavigationSiteChange[] | null;
    "groups": NavigationGroup[] | null;
}

export interface NavigationGroup {
    "id": string;
    "name": string;
    "items": NavigationItem[] | null;
}

export interface NavigationItem {
    "id": string;
    "title": string;
    "url": string;
    "icon": string;
    "description": string;
    "list": string;
    "size": string;
}

export interface NavigationSiteChange {
    "id": string;
    "title": string;
    "fromGroup": string;
    "fromList": string;
    "targetGroup": string;
    "targetList": string;
}
