// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchUpdateSites edits or moves one or many durable navigation records in a
 * single transaction. Selecting only SourceGroup moves every site in that Tab;
 * adding MatchSourceList narrows it to one list (including the empty list).
 */
export function BatchUpdateSites(request: $models.NavigationBatchUpdateRequest): $CancellablePromise<$models.NavigationBatchUpdateResult> {
    return $Call.ByID(542985443, request);
}

/**
 * DiscoverSiteIcon downloads the icon declared by a site, falling back to
 * /favicon.ico. Only validated image bytes are stored in Quick's config
 * directory, so navigation cards never need to contact the site to render it.
 * Calling this method again refreshes the cached file for the site.
 */
export function DiscoverSiteIcon(value: string): $CancellablePromise<string> {
    return $Call.ByID(1928255269, value);
}

/**
 * GetCachedSiteIcon returns a data URL backed by a validated local cache file.
 * The cache reference never allows path traversal outside navigation-icons.
 */
export function GetCachedSiteIcon(reference: string): $CancellablePromise<string> {
    return $Call.ByID(689403664, reference);
}

/**
 * GetNavigationGroups returns the durable navigation configuration. It does
 * not depend on the navigation page being mounted in the frontend.
 */
export function GetNavigationGroups(): $CancellablePromise<$models.NavigationGroup[] | null> {
    return $Call.ByID(935799654);
}
