export const FORMATTER_OPERATIONS = [
  "json-format",
  "json-minify",
  "yaml-format",
  "xml-format",
  "xml-minify",
  "html-format",
  "html-minify",
  "css-format",
  "css-minify",
  "javascript-format",
  "javascript-minify",
] as const
export const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"] as const
export const CONVERSION_MODULES = ["text", "naming", "standard", "encoding", "bytes", "code", "radix"] as const
export const TIME_OPERATIONS = [
  "timestamp-to-date",
  "date-to-timestamp",
  "timezone",
  "difference",
  "duration",
  "parse-duration",
  "generate",
  "cron",
] as const
export const VALIDATION_MODES = ["jsonpath", "json-schema", "xpath", "selector", "glob", "regex"] as const
export const VALIDATION_ACTIONS = ["run", "replace", "test-cases", "show-code"] as const
export const CRYPTO_OPERATIONS = [
  "hash",
  "hmac",
  "aes-encrypt",
  "aes-decrypt",
  "rsa-generate-encryption",
  "rsa-generate-signing",
  "rsa-encrypt",
  "rsa-decrypt",
  "rsa-sign",
  "rsa-verify",
  "jwt-parse",
  "jwt-sign",
  "jwt-verify",
] as const
export const NETWORK_OPERATIONS = [
  "ping",
  "dns",
  "port",
  "cidr",
  "url-inspect",
  "http-prepare",
  "http-execute",
  "curl-to-http",
  "http-to-curl",
  "process-search",
  "process-terminate",
] as const
export const FILE_RENAME_ACTIONS = ["prepare", "execute", "undo", "inspect"] as const
export const FRONTEND_OPERATIONS = ["color", "contrast", "gradient", "units", "svg-data-url"] as const
export const FILE_RENAME_OPERATIONS = ["reset", "replace", "prefix", "suffix"] as const
export const NAVIGATION_ACTIONS = ["list", "open", "prepare", "add", "update", "move", "batch-update", "delete"] as const
export const SIDEBAR_ACTIONS = ["list", "move"] as const

export const TOOL_INPUT_SCHEMAS = {
  formatter: {
    type: "object",
    properties: {
      operation: { type: "string", enum: [...FORMATTER_OPERATIONS], description: "格式化页面的操作 ID" },
      input: { type: "string", description: "写入格式化页面的完整输入" },
    },
    required: ["operation", "input"],
    additionalProperties: false,
  },
  converter: {
    type: "object",
    properties: {
      module: { type: "string", enum: [...CONVERSION_MODULES], description: "naming/standard/encoding/bytes/code/radix" },
      source: { type: "string", description: "来源格式 ID；例如 json、yaml、text、hex、10" },
      target: { type: "string", description: "目标格式 ID；例如 yaml、camel、base64、go、16" },
      input: { type: "string", description: "待转换的完整内容" },
    },
    required: ["module", "source", "target", "input"],
    additionalProperties: false,
  },
  "time-ids": {
    type: "object",
    properties: {
      operation: { type: "string", enum: [...TIME_OPERATIONS] },
      value: { type: "string", description: "时间戳、ISO 日期时间或时长数值" },
      unit: { type: "string", enum: ["seconds", "milliseconds"] },
      durationUnit: { type: "string", enum: ["milliseconds", "seconds", "minutes"], description: "duration 操作的输入单位" },
      sourceZone: { type: "string" },
      targetZone: { type: "string" },
      start: { type: "string" },
      end: { type: "string" },
      generator: { type: "string", enum: ["uuid", "guid", "ulid", "snowflake", "string", "number", "password"] },
      length: { type: "number", minimum: 1, maximum: 4096 },
      cron: { type: "string" },
      zone: { type: "string" },
    },
    required: ["operation"],
    additionalProperties: false,
  },
  validation: {
    type: "object",
    properties: {
      action: { type: "string", enum: [...VALIDATION_ACTIONS] },
      mode: { type: "string", enum: [...VALIDATION_MODES] },
      expression: { type: "string", description: "表达式；show-code 也应传入当前表达式" },
      input: { type: "string", description: "run 时的完整输入" },
      flags: { type: "string", description: "JavaScript 正则 Flags，仅 dgimsuvy" },
      replacement: { type: "string" },
      testCases: {
        type: "array",
        maxItems: 100,
        items: {
          type: "object",
          properties: { label: { type: "string" }, input: { type: "string" }, expected: { type: "boolean" } },
          required: ["input", "expected"],
          additionalProperties: false,
        },
      },
      language: { type: "string", enum: ["javascript", "typescript", "python", "csharp", "java", "go", "rust", "php"] },
      code: { type: "string" },
      explanation: { type: "string" },
    },
    required: ["mode"],
    additionalProperties: false,
  },
  frontend: {
    type: "object",
    properties: {
      operation: { type: "string", enum: [...FRONTEND_OPERATIONS] },
      foreground: { type: "string", description: "HEX 颜色" },
      background: { type: "string", description: "HEX 颜色" },
      angle: { type: "number" },
      pixels: { type: "number" },
      baseSize: { type: "number" },
      viewportWidth: { type: "number" },
      svg: { type: "string" },
    },
    required: ["operation"],
    additionalProperties: false,
  },
  crypto: {
    type: "object",
    properties: {
      operation: { type: "string", enum: [...CRYPTO_OPERATIONS] },
      input: { type: "string" },
      algorithm: { type: "string", enum: ["MD5", "SHA-1", "SHA-256", "SHA-512"] },
      signature: { type: "string" },
      publicKey: { type: "string", description: "仅公钥；不要提供私钥" },
    },
    required: ["operation"],
    additionalProperties: false,
  },
  network: {
    type: "object",
    properties: {
      operation: { type: "string", enum: [...NETWORK_OPERATIONS] },
      host: { type: "string" },
      count: { type: "number", minimum: 1, maximum: 20, description: "Ping 次数" },
      timeoutMS: { type: "number", minimum: 100, maximum: 60000, description: "Ping 总超时毫秒数" },
      packetSize: { type: "number", minimum: 1, maximum: 65500, description: "Ping 数据包字节数" },
      port: { type: "number", minimum: 1, maximum: 65535 },
      recordType: { type: "string", enum: ["A", "AAAA", "CNAME", "MX", "NS", "TXT"] },
      cidr: { type: "string" },
      method: { type: "string", enum: [...HTTP_METHODS] },
      url: { type: "string" },
      headers: { type: "string", description: "每行 Header: value；不要放入秘密" },
      body: { type: "string" },
      curl: { type: "string" },
      searchType: { type: "string", enum: ["port", "pid", "name"] },
      query: { type: "string" },
      pid: { type: "number", minimum: 1, description: "仅用于关闭刚刚通过带条件搜索得到的进程" },
    },
    required: ["operation"],
    additionalProperties: false,
  },
  "text-workbench": {
    type: "object",
    properties: {
      mode: { type: "string", enum: ["markdown", "diff"] },
      markdown: { type: "string" },
      left: { type: "string" },
      right: { type: "string" },
      granularity: { type: "string", enum: ["line", "word", "char"] },
      ignoreWhitespace: { type: "boolean" },
    },
    required: ["mode"],
    additionalProperties: false,
  },
  "file-tools": {
    type: "object",
    properties: {
      action: { type: "string", enum: [...FILE_RENAME_ACTIONS] },
      algorithm: { type: "string", enum: ["MD5", "SHA-256", "SHA-512"] },
      matchMode: { type: "string", enum: ["all", "wildcard", "regex"] },
      matchPattern: { type: "string" },
      matchFullName: { type: "boolean" },
      operation: { type: "string", enum: [...FILE_RENAME_OPERATIONS] },
      find: { type: "string" },
      replacement: { type: "string" },
      useRegex: { type: "boolean" },
      prefix: { type: "string" },
      suffix: { type: "string" },
      start: { type: "number" },
      step: { type: "number" },
      width: { type: "number", minimum: 1, maximum: 12 },
      includeExtension: { type: "boolean" },
      sortBy: { type: "string", enum: ["name", "modified", "size"] },
    },
    required: ["action"],
    additionalProperties: false,
  },
  navigation: {
    type: "object",
    properties: {
      action: { type: "string", enum: [...NAVIGATION_ACTIONS] },
      name: { type: "string", description: "open/update/move/delete 时用于定位记录的当前准确站点名称" },
      names: { type: "array", items: { type: "string" }, description: "batch-update 要处理的一组准确站点名称" },
      ids: { type: "array", items: { type: "string" }, description: "batch-update 要处理的一组站点 ID；优先使用 list 返回的 ID" },
      sourceGroup: { type: "string", description: "batch-update 的来源 group；不提供 names/ids 时表示选择该 group 下的全部站点" },
      sourceList: { type: "string", description: "batch-update 的来源 list；与 sourceGroup 组合筛选，空字符串可匹配未分 list 的站点" },
      targetGroup: { type: "string", description: "batch-update 移动到的现有 group" },
      targetList: { type: "string", description: "batch-update 移动到的 list；空字符串表示移出 list" },
      group: { type: "string", description: "新增或单项移动后的一级 Tab 分组名称" },
      list: { type: "string", description: "新增或单项移动后的 list；空字符串表示移出 list" },
      title: { type: "string", description: "新增站点标题，或只选择一个站点时的新标题" },
      url: { type: "string" },
      icon: { type: "string" },
      description: { type: "string", description: "站点说明；批量操作时会应用到全部匹配项，空字符串表示清空" },
      size: { type: "string", enum: ["1x1", "2x2", "4x2"] },
    },
    required: ["action"],
    additionalProperties: false,
  },
  "mcp-inspector": {
    type: "object",
    properties: {
      profileName: { type: "string", description: "设置页保存的 MCP 名称" },
      transport: { type: "string", enum: ["streamable-http", "sse", "stdio"] },
      url: { type: "string" },
      command: { type: "string" },
      argsJSON: { type: "string", description: "STDIO 参数 JSON 数组" },
      cwd: { type: "string" },
    },
    additionalProperties: false,
  },
}
